# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://pa.trick-raths.ch
title: Patrick Raths
email: p@trick-raths.ch
description: > # "Beschreibung"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com
  - title: github
    url: https://github.com/p-raths
  - title: facebook
    url: https://facebook.com/patrick.raths.56

